% ensure we have a consistent template for autogenerated revisions
"""
Revision ID: ${up_revision}
Revises: ${down_revision | commacomma}
Create Date: ${create_date}

"""
from alembic import op
import sqlalchemy as sa

${imports if imports}

def upgrade():
    ${upgrades if upgrades else 'pass'}


def downgrade():
    ${downgrades if downgrades else 'pass'}
