import os
import logging
from typing import Dict, Any, List, Optional
from .base_provider import BaseImageProvider, ProviderFeature
from google import genai
import httpx
from PIL import Image
from io import BytesIO
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from utils import save_pil_image, get_image_url

logger = logging.getLogger(__name__)


class GeminiProvider(BaseImageProvider):
    """
    Google Gemini Provider with Image Generation
    Uses google-genai SDK.
    
    Prompts are centralized in config/prompts/provider_prompts.py
    """

    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY not found in environment")

        self.client = genai.Client(api_key=self.api_key)
        self._http_client = httpx.AsyncClient(timeout=120.0)

    @property
    def provider_name(self) -> str:
        return "gemini"

    def get_supported_features(self) -> List[ProviderFeature]:
        return [
            ProviderFeature.GENERATE,
            ProviderFeature.EDIT,
            ProviderFeature.IMAGE_TO_IMAGE,
            ProviderFeature.UPSCALE,
        ]

    # -----------------------------
    # Image generation
    # -----------------------------
    async def generate_image(
        self,
        prompt: str,
        model: str = "gemini-3-pro-image-preview",
        aspect_ratio: str = "1:1",
        number_of_images: int = 1,
        style: str = "embroidery",
        leather_color: str = None,
        ink_color: str = None,
        font_style: str = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Generate images using Gemini models that support image generation.
        """

        available_models = [
            "gemini-3-pro-image-preview",
            "gemini-2.5-flash-image",
            "gemini-1.5-pro-latest",
        ]
        if model not in available_models:
            model = "gemini-3-pro-image-preview"

        # Use centralized prompts
        from config.prompts import provider_prompts
        enhanced_prompt = provider_prompts.build_generate_prompt(
            user_prompt=prompt,
            style=style,
            leather_color=leather_color,
            ink_color=ink_color,
            font_style=font_style,
        )

        results = []
        for attempt in range(number_of_images):
            try:
                response = self.client.models.generate_content(
                    model=model,
                    contents=enhanced_prompt,
                )

                if not getattr(response, "parts", None):
                    continue

                for part in response.parts:
                    if hasattr(part, "inline_data") and part.inline_data:
                        image = part.as_image()
                        filepath = save_pil_image(image, prefix="final_")
                        image_url = get_image_url(filepath)

                        results.append({"url": image_url, "local_path": filepath})

            except Exception as e:
                import traceback
                traceback.print_exc()

        if not results:
            raise ValueError(
                f"No images generated by Gemini ({model}). "
                "Possible reasons: 1) Text in images blocked by safety filters, "
                "2) Model doesn't support image generation via generate_content, "
                "3) Prompt triggered content policy. "
                "Try using Recraft or OpenAI instead."
            )

        return self.normalize_response(
            {"images": results, "model": model, "aspect_ratio": aspect_ratio}
        )

    # -----------------------------
    # Image editing
    # -----------------------------
    async def edit_image(
        self,
        image_url: str,
        prompt: str,
        model: str = "gemini-3-pro-image-preview",
        style: str = "embroidery",
        leather_color: str = None,
        ink_color: str = None,
        font_style: str = None,
        enhance_quality: bool = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Edit an image using Gemini with style presets + global "logo-only" guardrails.
        
        Automatically enhances quality if image is low-resolution or enhance_quality=True.
        This combines enhancement and editing in a single efficient call.
        """
        image_bytes = await self._download_image(image_url)
        pil_image = Image.open(BytesIO(image_bytes))
        
        # Auto-detect if enhancement is needed based on image resolution
        # Default to True if not explicitly set (smart enhancement)
        if enhance_quality is None:
            width, height = pil_image.size
            min_dimension = min(width, height)
            # Auto-enhance if image is below 1024px or if explicitly requested
            enhance_quality = min_dimension < 1024
            logger.info(f"Auto-detected enhance_quality={enhance_quality} (resolution: {width}x{height})")
        elif enhance_quality:
            logger.info("Enhancement explicitly requested")

        # Use centralized prompts
        from config.prompts import provider_prompts
        enhanced_prompt = provider_prompts.build_edit_prompt(
            edit_instruction=prompt,
            style=style,
            leather_color=leather_color,
            ink_color=ink_color,
            font_style=font_style,
            enhance_quality=enhance_quality,
        )

        try:
            response = self.client.models.generate_content(
                model=model,
                contents=[pil_image, enhanced_prompt],
            )

            if not getattr(response, "parts", None):
                raise ValueError(
                    "Gemini did not generate any image parts. "
                    f"Response: {response.text if hasattr(response, 'text') else 'No response text'}"
                )

            results = []
            for part in response.parts:
                if hasattr(part, "inline_data") and part.inline_data:
                    image = part.as_image()
                    filepath = save_pil_image(image, prefix="final_")
                    result_url = get_image_url(filepath)
                    results.append({"url": result_url, "local_path": filepath})

            if not results:
                raise ValueError("Gemini generated a response but no images. Try a different prompt or model.")

            return self.normalize_response({"images": results, "model": model})

        except Exception as e:
            raise ValueError(f"Gemini image editing failed: {str(e)}")

    async def image_to_image(self, image_url: str, prompt: str, **kwargs) -> Dict[str, Any]:
        """Image-to-image transformation"""
        return await self.edit_image(image_url, prompt, **kwargs)

    async def analyze_image(self, image_url: str, **kwargs) -> Dict[str, Any]:
        """
        Analyze an image using Gemini vision to determine quality and recommend processing.
        Returns insights about resolution, content type, and whether it needs upscaling/vectorization.
        """
        logger.info(f"GeminiProvider.analyze_image started for url: {image_url[:100]}")
        try:
            # Download and open image to get technical details
            image_bytes = await self._download_image(image_url)
            pil_image = Image.open(BytesIO(image_bytes))
            
            width, height = pil_image.size
            format_type = pil_image.format or "Unknown"
            mode = pil_image.mode
            
            # Calculate color complexity for vectorization assessment
            try:
                if pil_image.mode in ['P', 'L', 'RGB', 'RGBA']:
                    # Quantize to count unique colors (max 256 for speed)
                    quantized = pil_image.quantize(colors=256) if pil_image.mode != 'P' else pil_image
                    colors = quantized.getcolors(maxcolors=256)
                    num_colors = len(colors) if colors else 256
                else:
                    num_colors = 256  # Default for complex modes
            except:
                num_colors = 256
            
            logger.debug(f"Estimated colors: {num_colors}")
            
            # Use Gemini vision to analyze content
            logger.debug("Calling Gemini vision API")
            from config.prompts import provider_prompts
            analysis_prompt = provider_prompts.GEMINI_ANALYSIS_PROMPT

            response = self.client.models.generate_content(
                model="gemini-3-pro-image-preview",
                contents=[pil_image, analysis_prompt]
            )
            
            ai_analysis = response.text if hasattr(response, 'text') else "Analysis unavailable"
            logger.info(f"Gemini vision analysis completed: {len(ai_analysis)} chars")
            
            # Detect style from AI analysis
            detected_style = self._detect_style_from_analysis(ai_analysis)
            logger.info(f"Detected style: {detected_style}")
            
            # Determine recommendations based on technical + AI analysis
            recommendations = []
            reasons = []
            
            # Resolution check
            min_dimension = min(width, height)
            needs_enhance = min_dimension < 1024
            if needs_enhance:
                recommendations.append("enhance")
                reasons.append(f"Resolution {width}x{height} is below 1024px - enhance for better quality")
            
            # Vectorization suitability (simple heuristics + AI)
            ai_lower = ai_analysis.lower()
            is_logo_like = any(word in ai_lower for word in ['logo', 'icon', 'emblem', 'badge', 'symbol'])
            is_simple = num_colors < 64 or 'flat' in ai_lower or 'simple' in ai_lower
            is_complex_photo = any(word in ai_lower for word in ['photograph', 'photo', 'realistic', 'gradient'])
            
            vectorization_score = 1
            if is_logo_like:
                vectorization_score += 2
            if is_simple:
                vectorization_score += 1
            if num_colors < 32:
                vectorization_score += 1
            if is_complex_photo:
                vectorization_score -= 2
            
            suitable_for_vector = vectorization_score >= 3
            if suitable_for_vector:
                recommendations.append("vectorize")
                reasons.append(f"Suitable for vectorization (score: {vectorization_score}/5, {num_colors} colors)")
            else:
                reasons.append(f"Not ideal for vectorization (score: {vectorization_score}/5, too complex)")
            
            # Determine optimal workflow
            if needs_enhance and suitable_for_vector:
                workflow = "enhance_then_vectorize"
                workflow_description = "1. Enhance with Gemini to 1024px+ for better quality, 2. Then vectorize for SVG output"
            elif suitable_for_vector:
                workflow = "vectorize_only"
                workflow_description = "Vectorize directly - resolution is sufficient"
            elif needs_enhance:
                workflow = "enhance_only"
                workflow_description = "Enhance with Gemini for better quality (not suitable for vectorization)"
            else:
                workflow = "use_as_is"
                workflow_description = "Image is good quality but complex - keep as raster"
            
            logger.info(f"Analysis complete - workflow: {workflow}, recommendations: {recommendations}")
            
            return self.normalize_response({
                "analysis": {
                    "technical": {
                        "resolution": f"{width}x{height}",
                        "width": width,
                        "height": height,
                        "format": format_type,
                        "color_mode": mode,
                        "estimated_colors": num_colors,
                        "file_size_kb": len(image_bytes) // 1024
                    },
                    "ai_assessment": ai_analysis,
                    "detected_style": detected_style,
                    "recommendations": {
                        "actions": recommendations,
                        "reasons": reasons,
                        "needs_enhance": needs_enhance,
                        "suitable_for_vectorization": suitable_for_vector,
                        "vectorization_score": f"{vectorization_score}/5"
                    },
                    "optimal_workflow": {
                        "name": workflow,
                        "description": workflow_description,
                        "steps": recommendations
                    }
                }
            })
            
        except Exception as e:
            logger.error(f"analyze_image failed: {str(e)}", exc_info=True)
            return self.normalize_response({
                "analysis": {
                    "error": str(e),
                    "message": "Analysis failed - proceeding with default recommendations"
                }
            })

    async def upscale_image(
        self,
        image_url: str,
        upscale_factor: str = "x2",
        style: str = None,
        **kwargs,
    ) -> Dict[str, Any]:
        """
        Enhance image with style-aware quality improvement.
        Uses edit_image with enhancement enabled (simplified - no duplicate code).
        """
        logger.info(f"Enhancing image with style: {style}")
        
        # Use edit_image with enhancement enabled - it handles both editing and enhancement
        # This avoids duplicate code and uses the same proven enhancement logic
        enhancement_prompt = "Enhance this image quality: sharpen edges, remove artifacts, improve resolution, make text crisp and legible. Preserve all design elements, colors, and composition exactly as they are."
        
        return await self.edit_image(
            image_url=image_url,
            prompt=enhancement_prompt,
            style=style or "embroidery",
            enhance_quality=True,
            **kwargs
        )

    def _detect_style_from_analysis(self, analysis_text: str) -> str:
        """
        Detect style from AI analysis text (legacy fallback).
        Prefer JSON analysis from centralized prompts.
        
        Args:
            analysis_text: AI-generated analysis text
            
        Returns:
            Detected style name or None
        """
        from config.prompts import provider_prompts
        return provider_prompts.detect_style_from_text(analysis_text)
    
    async def _download_image(self, url: str) -> bytes:
        """Download image from URL or decode from base64 (with caching)"""
        if url.startswith("data:"):
            import base64

            header, encoded = url.split(",", 1)
            return base64.b64decode(encoded)

        # Use cached download
        from utils.image_cache import download_image_cached
        return await download_image_cached(url, self._http_client)

    def get_available_models(self) -> List[str]:
        return [
            "gemini-3-pro-image-preview",
            "gemini-2.0-flash-exp",
            "gemini-1.5-flash",
            "gemini-1.5-pro",
        ]
